name: Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip3 install pylint coverage

    - name: Run tests
      run: pylint --errors-only full_offline_backup_for_todoist && coverage run -m unittest && coverage lcov

    - name: Upload coverage report
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
