name: Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip3 install pylint mypy coverage

    - name: Run linters
      run: pylint --errors-only full_offline_backup_for_todoist && mypy --strict -m full_offline_backup_for_todoist

    - name: Run tests
      run: coverage run -m unittest && coverage lcov

    - name: Upload coverage report
      uses: coverallsapp/github-action@v1.2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
